name: Docker Image CI/CD

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]


jobs:
  build:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Stop and Remove Existing Container (if exists)
        run: |
          if [ "$(docker ps -q -f name=my_container)" ]; then
            docker stop my_container && docker rm my_container
          fi

      - name: Remove Old Docker Image (if exists)
        run: |
          if [ "$(docker images -q my_image:latest)" ]; then
            docker rmi my_image:latest
          fi

      - name: Build Docker Image
        run: docker build -t my_image:latest .

      - name: Run Docker Container
        run: |
          docker run -d --name my_container -p 80:80 my_image:latest
